<?php

declare(strict_types=1);

namespace packages\domain\model\facility\workplace;

use Ramsey\Collection\Collection;
use Traversable;

class WorkplaceList extends Collection
{
    /**
     * @param Workplace[]|null $list
     * @return Workplace[]
     */
    public function __construct(array $list = null)
    {
        parent::__construct(Workplace::class);

        if (!empty($list)) {
            $this->setList($list);
        }
    }

    /**
     * @param array $list
     * @return void
     */
    private function setList(array $list)
    {
        foreach ($list as $item) {
            $this->add($item);
        }
    }

    /**
     * @return Workplace[]
     */
    public function getIterator(): Traversable
    {
        return parent::getIterator(); // TODO: Change the autogenerated stub
    }

    /**
     * 連想配列にコンバートします
     * @return array
     */
    public function toArray(): array
    {
        return parent::toArray();
    }
}
