<?php

declare(strict_types=1);

namespace packages\domain\model\batch;

use Ramsey\Collection\Collection;
use Traversable;

class MigrationBatchAuditList extends Collection
{
    /**
     * @param MigrationBatchAudit[]|null $migrationBatchAuditList
     * @return MigrationBatchAudit[]
     */
    public function __construct(array $migrationBatchAuditList = null)
    {
        parent::__construct(MigrationBatchAudit::class);

        if (!empty($migrationBatchAuditList)) {
            $this->setList($migrationBatchAuditList);
        }
    }

    /**
     * @param array $list
     * @return void
     */
    private function setList(array $list)
    {
        foreach ($list as $item) {
            $this->add($item);
        }
    }

    /**
     * @return MigrationBatchAudit[]
     */
    public function getIterator(): Traversable
    {
        return parent::getIterator(); // TODO: Change the autogenerated stub
    }

    /**
     * 連想配列にコンバートします
     * @return array
     */
    public function toArray(): array
    {
        return parent::toArray();
    }
}
