<?php

declare(strict_types=1);

namespace packages\domain\model\prefecture;

use Ramsey\Collection\Collection;
use Traversable;

class PrefectureList extends Collection
{
    /**
     * @param Prefecture[]|null $prefectureList
     * @return Prefecture[]
     */
    public function __construct(array $prefectureList = null)
    {
        parent::__construct(Prefecture::class);

        if (!empty($prefectureList)) {
            $this->setList($prefectureList);
        }
    }

    /**
     * @param array $list
     * @return void
     */
    private function setList(array $list)
    {
        foreach ($list as $item) {
            $this->add($item);
        }
    }

    /**
     * @return Campaign[]
     */
    public function getIterator(): Traversable
    {
        return parent::getIterator(); // TODO: Change the autogenerated stub
    }

    /**
     * 連想配列にコンバートします
     * @return array
     */
    public function toArray(): array
    {
        return parent::toArray();
    }
}
