openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: M
servers:
  - url: http://petstore.swagger.io/v1
paths:
  $ref: './paths/index.yml'
components:
  $ref: './components/index.yml'