<?php

declare(strict_types=1);

namespace packages\domain\model\zipcode;

use Ramsey\Collection\Collection;
use Traversable;

class YuseiZipDiffList extends Collection
{
    /**
     * @return ZipCodeSourceDiffList[]
     */
    public function __construct()
    {
        parent::__construct(ZipCodeSourceDiffList::class);
    }

    /**
     * @return ZipCodeSourceDiffList[]
     */
    public function getIterator(): Traversable
    {
        return parent::getIterator(); // TODO: Change the autogenerated stub
    }

    /**
     * 連想配列にコンバートします
     * @return array
     */
    public function toArray(): array
    {
        $toArray = [];
        foreach ($this->data as $key => $data) {
            $toArray[$key] = $data;
        }
        return $toArray;
    }
}
